import os

# PROJECT
PROJECT_TITLE = os.getenv("PROJECT_TITLE")
PROJECT_DESC = os.getenv("PROJECT_DESC")
PROJECT_VERSION = os.getenv("PROJECT_VERSION")
OPENAPI_JSON = "/api/v1/connectivity.json"

# POSTGRES
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
SQLALCHEMY_DATABASE_URI = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}/{POSTGRES_DB}"

# REDIS
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_DB = os.getenv("REDIS_DB")

# API
API_V1_STR = os.getenv("API_V1_STR")

# SECURITY APIKEY
APIKEY_HEADER_NAME = os.getenv("APIKEY_HEADER_NAME")
APIKEY_HEADER_TOKEN = os.getenv("APIKEY_HEADER_TOKEN")

# TEMPLATES CONF
